[package]
name = "kirl_parser"
version = "0.1.0"
authors = ["White-Green <43771790+White-Green@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenizer = { git = "https://github.com/White-Green/Yet-Another-Rust-Parser", rev = "74ebf625f6540f899983ae7a3be1b148761a716f" }
parser = { git = "https://github.com/White-Green/Yet-Another-Rust-Parser", rev = "74ebf625f6540f899983ae7a3be1b148761a716f" }
