[package]
name = "kirl_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dec = "0.4.5"
once_cell = "1.8.0"
